# Generated by Django 5.2.7 on 2026-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('road', 'Road Trip'), ('flight', 'Flight Trip')], max_length=20)),
                ('min_distance', models.FloatField(default=0)),
                ('max_distance', models.FloatField(default=100000)),
            ],
        ),
    ]
